### 注册用户
POST http://***/api/auth/register
Content-Type: application/json

{
    "username": "***",
    "password": "***"
}

### 登录用户
POST http://***/api/auth/login
Content-Type: application/json

{
    "username": "***",
    "password": "***"
}

### 测试认证接口（带Token）
GET http://***/api/test
Authorization: 

### 发送消息
POST http://***/api/chat/send
Authorization: 
Content-Type: application/json

{
    "message": "你好，你是奶龙"
}

### 测试历史记录
GET http://***/api/chat/history
Authorization: 
### 1. 获取验证码
GET http://***/api/captcha/get

### 2. 验证码登录
POST http://***/api/auth/login
Content-Type: application/json
